version: '3.4'

services:
  tasking.api:
    image: ${DOCKER_REGISTRY-}taskmanagementwebapi
    build:
      context: .
      dockerfile: TaskService/Tasking.API/Dockerfile

  taskmanagementui:
    image: ${DOCKER_REGISTRY-}taskmanagementui
    build:
      context: ../../taskmanagementui
      dockerfile: Dockerfile
  
  managementdb:
    image: mcr.microsoft.com/mssql/server:2022-preview-ubuntu-22.04

  
